### ISSUE TITLE
main.php doesn't display current variable values

### ISSUE THREAD

**Issue by floppyMike** [wssct20/ProjectSpyder#1]
**Describe the bug**
After changing a value of a device variable the values on `main.php` won't update. Specifically the displayed values won't change after modifying them through `devices.php`.

**To Reproduce**
1. List a device with modifiable variables
2. Go to `devices.php`
3. Click on `Manage`
4. Modify a variable and click `Overwrite`
5. Look at the value in `main.php`

**Expected behavior**
The value of the device variable should change to the value given.

**Comment by programminghoch10** [comment]
`main.php` displays the friendly values if they are available.
If there are no friendly values available the raw data will be displayed.

Handling of friendly values is to be handled by the client.
When the client sees a change in raw data, it should update the friendly data accordingly as well as react if it is an actor.
This is needed, because the system cannot for example translate a button's binary state  (raw data: 0 or 1) into `pressed` and `released`.
As an actor you should expect changes in the raw data and update the friendly values accordingly.
As an sensor you can prevent the user from editing those values by not specifying them in `usermodifiabledata`.

You can convince yourself by testing with this JSON structure:
`{"data":{"state":0},"usermodifiabledata":["state"],"preferredupdatetime":30}`
Again, notice how its missing the `friendly` section, which forces the system to show raw values.

When updating sensor values as a client, always also update the friendly values!

**Comment by floppyMike** [comment]
Ah I understand. By not having `datavalue` the raw value gets used. Thanks for clearing it up.
